export const navigatiocollection = [
  {
    id: 1,
    label: "Navigation",
    hyperef1: "#header",
    blank1: false,
    link1: "home",
    hyperef2: "#services",
    blank2: false,
    link2: "services",
    hyperef3: "#tyoh",
    blank3: false,
    link3: "tyoh",
  },
  {
    id: 2,
    label: "Links",
    hyperef1: "https://x.com/Microsoft",
    blank1: true,
    link1: "Discord",
    hyperef2: "https://x.com/Microsoft",
    blank2: true,
    link2: "Twitter",
    hyperef3: "",
    blank3: true,
    link3: "",
  },
  {
    id: 3,
    label: "Contact",
    hyperef1: "#footer",
    blank1: false,
    link1: "Microsoft#7007",
    hyperef2: "#footer",
    blank2: false,
    link2: "Microsoft",
    hyperef3: "mailto:microsoft@gmail.com",
    blank3: false,
    link3: "microsoft@gmail.com",
  },
];
